Added topics, subscription and callback
De-Druppel/DruppelController pull request #9
Opened 2020-10-13 07:25 UTC by Alduthir

2020-10-13 21:38 UTC, dmeuwissen requested changes, later dismissed

2020-10-13 21:38 UTC, dmeuwissen commented on src/main.cpp
> +  pubsubClient.setCallback(callback);
Mogelijk verplaatsen naar de configureMQTTClient functie.

2020-10-13 21:38 UTC, dmeuwissen commented on src/main.cpp
> +  if(!wifiClient.connected())
Moeten we donderdag even bespreken.

2020-10-13 21:38 UTC, dmeuwissen commented on src/main.cpp
> +  if(pubsubClient.connected())
Donderdag even bespreken.

2020-10-15 16:47 UTC, quatro32 approved these changes

2020-10-15 16:49 UTC, merged